using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Presonus.UC.Api.Components.Parameters
{
	public class FilterGroup : ParameterBase
	{
		public Param name = new("Filter Group Name", ParamType.STRING);
		public Param groupnum = new("Filter Group Number", ParamType.STRING);
		public Param solo = new("Master Solo", ParamType.TOGGLE);
		public Param iconid = new("Channel Icon ID", ParamType.STRING);
		public Param select = new("Select", ParamType.TOGGLE);
		public Param mute = new("Master Mute", ParamType.TOGGLE);
		public Param mute_aux1 = new("Aux 1 Mute", ParamType.TOGGLE);
		public Param mute_aux2 = new("Aux 2 Mute", ParamType.TOGGLE);
		public Param mute_aux3 = new("Aux 3 Mute", ParamType.TOGGLE);
		public Param mute_aux4 = new("Aux 4 Mute", ParamType.TOGGLE);
		public Param mute_aux5 = new("Aux 5 Mute", ParamType.TOGGLE);
		public Param mute_aux6 = new("Aux 6 Mute", ParamType.TOGGLE);
		public Param mute_aux7 = new("Aux 7 Mute", ParamType.TOGGLE);
		public Param mute_aux8 = new("Aux 8 Mute", ParamType.TOGGLE);
		public Param mute_aux9 = new("Aux 9 Mute", ParamType.TOGGLE);
		public Param mute_aux10 = new("Aux 10 Mute", ParamType.TOGGLE);
		public Param mute_aux11 = new("Aux 11 Mute", ParamType.TOGGLE);
		public Param mute_aux12 = new("Aux 12 Mute", ParamType.TOGGLE);
		public Param mute_aux13 = new("Aux 13 Mute", ParamType.TOGGLE);
		public Param mute_aux14 = new("Aux 14 Mute", ParamType.TOGGLE);
		public Param mute_aux15 = new("Aux 15 Mute", ParamType.TOGGLE);
		public Param mute_aux16 = new("Aux 16 Mute", ParamType.TOGGLE);
		public Param mute_aux17 = new("Aux 17 Mute", ParamType.TOGGLE);
		public Param mute_aux18 = new("Aux 18 Mute", ParamType.TOGGLE);
		public Param mute_aux19 = new("Aux 19 Mute", ParamType.TOGGLE);
		public Param mute_aux20 = new("Aux 20 Mute", ParamType.TOGGLE);
		public Param mute_aux21 = new("Aux 21 Mute", ParamType.TOGGLE);
		public Param mute_aux22 = new("Aux 22 Mute", ParamType.TOGGLE);
		public Param mute_aux23 = new("Aux 23 Mute", ParamType.TOGGLE);
		public Param mute_aux24 = new("Aux 24 Mute", ParamType.TOGGLE);
		public Param mute_aux25 = new("Aux 25 Mute", ParamType.TOGGLE);
		public Param mute_aux26 = new("Aux 26 Mute", ParamType.TOGGLE);
		public Param mute_aux27 = new("Aux 27 Mute", ParamType.TOGGLE);
		public Param mute_aux28 = new("Aux 28 Mute", ParamType.TOGGLE);
		public Param mute_aux29 = new("Aux 29 Mute", ParamType.TOGGLE);
		public Param mute_aux30 = new("Aux 30 Mute", ParamType.TOGGLE);
		public Param mute_aux31 = new("Aux 31 Mute", ParamType.TOGGLE);
		public Param mute_aux32 = new("Aux 32 Mute", ParamType.TOGGLE);
		public Param mute_fx1 = new("FX A Mute", ParamType.TOGGLE);
		public Param mute_fx2 = new("FX B Mute", ParamType.TOGGLE);
		public Param mute_fx3 = new("FX C Mute", ParamType.TOGGLE);
		public Param mute_fx4 = new("FX D Mute", ParamType.TOGGLE);
		public Param mute_fx5 = new("FX E Mute", ParamType.TOGGLE);
		public Param mute_fx6 = new("FX F Mute", ParamType.TOGGLE);
		public Param mute_fx7 = new("FX G Mute", ParamType.TOGGLE);
		public Param mute_fx8 = new("FX H Mute", ParamType.TOGGLE);
		public Param volume;
		public Param aux1;
		public Param aux2;
		public Param aux3;
		public Param aux4;
		public Param aux5;
		public Param aux6;
		public Param aux7;
		public Param aux8;
		public Param aux9;
		public Param aux10;
		public Param aux11;
		public Param aux12;
		public Param aux13;
		public Param aux14;
		public Param aux15;
		public Param aux16;
		public Param aux17;
		public Param aux18;
		public Param aux19;
		public Param aux20;
		public Param aux21;
		public Param aux22;
		public Param aux23;
		public Param aux24;
		public Param aux25;
		public Param aux26;
		public Param aux27;
		public Param aux28;
		public Param aux29;
		public Param aux30;
		public Param aux31;
		public Param aux32;
		public Param fx1;
		public Param fx2;
		public Param fx3;
		public Param fx4;
		public Param fx5;
		public Param fx6;
		public Param fx7;
		public Param fx8;
		public Param asn_flags_1_32 = new("Assign Flags line 1-32", ParamType.COLOR);
		public Param asn_flags_33_64 = new("Assign Flags line 33-64", ParamType.COLOR);
		public Param asn_flags_fxret_ret = new("Assign Flags fxret/ret", ParamType.COLOR);
		public Param line1;
		public Param line2;
		public Param line3;
		public Param line4;
		public Param line5;
		public Param line6;
		public Param line7;
		public Param line8;
		public Param line9;
		public Param line10;
		public Param line11;
		public Param line12;
		public Param line13;
		public Param line14;
		public Param line15;
		public Param line16;
		public Param line17;
		public Param line18;
		public Param line19;
		public Param line20;
		public Param line21;
		public Param line22;
		public Param line23;
		public Param line24;
		public Param line25;
		public Param line26;
		public Param line27;
		public Param line28;
		public Param line29;
		public Param line30;
		public Param line31;
		public Param line32;
		public Param line33;
		public Param line34;
		public Param line35;
		public Param line36;
		public Param line37;
		public Param line38;
		public Param line39;
		public Param line40;
		public Param line41;
		public Param line42;
		public Param line43;
		public Param line44;
		public Param line45;
		public Param line46;
		public Param line47;
		public Param line48;
		public Param line49;
		public Param line50;
		public Param line51;
		public Param line52;
		public Param line53;
		public Param line54;
		public Param line55;
		public Param line56;
		public Param line57;
		public Param line58;
		public Param line59;
		public Param line60;
		public Param line61;
		public Param line62;
		public Param line63;
		public Param line64;
		public Param fxreturn1;
		public Param fxreturn2;
		public Param fxreturn3;
		public Param fxreturn4;
		public Param fxreturn5;
		public Param fxreturn6;
		public Param fxreturn7;
		public Param fxreturn8;
		public Param return1;
		public Param return2;
		public Param return3;
		public Param return4;

		public FilterGroup(string path) : base(path)
		{
		}
	}
}
